feat: add plural forms
skondurushkin/ilp pull request #132
Opened 2023-04-10 23:03 UTC by nikolaas

2023-04-10 23:14 UTC, stasian33rus approved these changes

2023-04-11 07:10 UTC, alprtv approved these changes

2023-04-11 07:11 UTC, alprtv requested changes

2023-04-11 07:11 UTC, alprtv commented on frontend/src/components/WalletCard.tsx
> +                <span className="text-3xl text-white">{plural(wallet.balance, ['вольт', 'вольта', 'вольт'])}</span>
я бы еще хелпер сделал, чтобы каждый раз не писать ['вольт', 'вольта', 'вольт']
тк plural там пока только для этого и нужен

2023-04-11 07:51 UTC, alprtv approved these changes

2023-04-11 07:52 UTC, merged