Feature/router
skondurushkin/ilp pull request #5
Opened 2023-03-14 20:13 UTC by alprtv

Сделал пример роутинга с разделением по ролям 
сама роль хранится в локалсторадже, тк хз пока что выберем реакт-квери или ртк 

для простоты использовал tsx объявление роутеров, потом можно будет заменить на объекты

так же добавил husky/lint-staged/stylelint
stylelint нужно будет сконфигурировать, как определимся через что пишем, под наши задачи

и openapi-generator-cli

2023-03-14 21:05 UTC, nikolaas requested changes

2023-03-14 21:05 UTC, nikolaas commented on frontend/src/api/index.ts
> +export const api = {
Давайте оставим просто:

```
export const api = new IlpApi(undefined, undefined, http.axios);
```

У нас ведь других api пока не предвидится. И кода писать меньше

2023-03-14 21:05 UTC, nikolaas commented on frontend/src/routers/AppRouter.tsx
> +    const RouterSwitch = {
Не совсем понял зачем так сложно. Какой то типизации тут нет. Можно упростить до:

```
const router = isAuthenticated ? <AuthUserRouter /> : <GuestRouter />;
```

2023-03-14 21:05 UTC, nikolaas commented on frontend/src/routers/AuthContext.ts
> +export const AuthContext = createContext<Partial<AuthContextProps>>({});
Не понял зачем нам этот контекст. Если его юзать то так: `useContext(AuthContext)`. Но ведь у нас уже есть хук `useAuthContext()`. Да, внутри он не юзает react-контекст, но функционал предоставляет тот же

2023-03-14 21:05 UTC, nikolaas commented on frontend/src/routers/components/TypedLink/TypedLink.tsx
> +export const TypedLink = <P extends RoutesPath>({
Давайте переименуем в `NavLink`? потому что эта ссылка позволяет указывать в качестве урла только роуты.

2023-03-14 21:05 UTC, nikolaas commented on frontend/src/routers/index.ts
> +/*
Вообще идея этого кода мне очень нравится. Не очень нравится, что лежит этот код в файле index.ts, Обычно файл index содержит экспортируемые из его директории элементы. Импортировать его внутри своей же директории это отличный шанс сделать циклические зависимости. Может это и не влялет на работоспособность, но код запутывает. функция buildUrl и ее сопуствующие типы используются только в TypedLink. Давайте туда и перенесем ее?

2023-03-14 21:05 UTC, nikolaas commented on frontend/src/routers/index.ts
> +export const ROUTES = PATHS.reduce(function (result, item) {
Не совсем понял для чего `ROUTES`. чтобы можно было быстро заменить урлы? но тогда же теряется все плюшки от `TypedLink`

2023-03-15 04:18 UTC, alprtv commented on frontend/src/api/index.ts
> +export const api = {
не факт, каждый тек в апи - это новое апи, бек может их сделать много
например
auth
user
admin
и тп по сущностям

2023-03-15 04:19 UTC, alprtv commented on frontend/src/routers/AppRouter.tsx
> +    const RouterSwitch = {
неа, удобно на каждую роль держать свой роутер
так что тут еще будет как минимум AuthAdminRouter

2023-03-15 04:20 UTC, alprtv commented on frontend/src/routers/components/TypedLink/TypedLink.tsx
> +export const TypedLink = <P extends RoutesPath>({
чтобы объявить провайдер
<AuthContext.Provider value={authContext}>

2023-03-15 04:21 UTC, alprtv commented on frontend/src/routers/index.ts
> +/*
разнесу по файлам, как делал на нашем проекте, только buildUrl не стоит в линку добавлять
тк бывают случаи, где он еще нужен бывает

2023-03-15 04:26 UTC, alprtv commented on frontend/src/routers/index.ts
> +export const ROUTES = PATHS.reduce(function (result, item) {
неа, на моем проекте, я роутинг по другому строил в плоском варианте и там ROUTES не нужно было делать
тк у нас изначально был одноуровневый массив со всеми роутами и типы строились по absolutePath
{
absolutePath: '/a/b
}
тут же нам нужен ROUTES не для типизации, а для того, чтобы руками не писать роуты в
компоненте react-router <Route to=ROUTES['/']/> те фактически только один раз на этапе архитектуры роута

я не хочу сюда добавлять тот вариант, который я на енс делал) тк я его делал, когда уже там работал
вдруг это какие то внутренние законы нарушает))

а этот код, он был сделан сильно раньше работы в люксе в свободное от работы время

2023-03-15 04:27 UTC, alprtv commented on frontend/src/routers/AuthContext.ts
> +export const AuthContext = createContext<Partial<AuthContextProps>>({});
чтобы объявить провайдер
<AuthContext.Provider value={authContext}>

2023-03-15 09:45 UTC, nikolaas commented on frontend/src/routers/AuthContext.ts
> +export const AuthContext = createContext<Partial<AuthContextProps>>({});
Так ведь можно просто юзать `useAuthContext()`, он ведь тоже самое возвращает (почти, юзера еще добавляет)

Зачем два способа получить одно и тоже, причем практически одинаковых

2023-03-15 10:21 UTC, nikolaas commented on frontend/src/routers/index.ts
> +export const ROUTES = PATHS.reduce(function (result, item) {
Тут, как договорились, нужен TypedRoute

2023-03-15 10:51 UTC, alprtv commented on frontend/src/routers/AuthContext.ts
> +export const AuthContext = createContext<Partial<AuthContextProps>>({});
поменял

2023-03-15 14:28 UTC, nikolaas approved these changes

2023-03-15 14:28 UTC, nikolaas commented on frontend/src/routers/AppRouter.tsx
> +    const { authContext, isAuthenticated } = useAuthContext();
Тут как договорились тоже нужно переделать:
1) `useAuthContext` вызывается только тут (и сам хук нужно спрятать от остального кода, чтобы не было соблазна его юзать еще где то)
2) данные которые создает `useAuthContext` засунуть в два реакт-контекста
3) на страницах (сейчас это `Dashboard` и `SignIn`) использовать реакт-контексты вместо `useAuthContext`

2023-03-15 14:44 UTC, alprtv commented on frontend/src/routers/AppRouter.tsx
> +    const { authContext, isAuthenticated } = useAuthContext();
ты 
Outdated
версию смотришь) уже все сделано

2023-03-15 14:46 UTC, nikolaas approved these changes

2023-03-15 14:48 UTC, merged