Feature/admin users
skondurushkin/ilp pull request #82
Opened 2023-04-06 19:44 UTC by alprtv

2023-04-06 19:57 UTC, nikolaas requested changes

2023-04-06 19:57 UTC, nikolaas commented on frontend/src/modules/admin/walltet.ts
>  export const WRITE_OFFS_ADMIN_PAGE_QUERY_KEY = 'admin.browseWriteOffsAsAdmin';
файл наверно должен был называться wallet.ts

2023-04-06 19:57 UTC, nikolaas commented on frontend/src/pages/UserAdminPage/EditBalanceForm.tsx
> +    const loadOptions = debounce(async (globalFilter: string) => {
в `react-use` есть хук `useDebounce` (https://github.com/streamich/react-use/blob/master/docs/useDebounce.md). он не подойдет? если подойдет то можно не добавлять новую либу `debounce-promise`

Кстати у нас еще есть компонент `DebouncedInput`, там тоже можно переделать, если хук подойдет

2023-04-06 19:57 UTC, nikolaas commented on frontend/src/pages/UsersAdminPage/UsersAdminPage.tsx
> +    const handleSearchKey = useCallback((value: string) => {
это ж просто обертка, можно обойтись без нее

`<SearchInput value={searchKey} onChange={setSearchKey} />`

2023-04-07 05:57 UTC, alprtv commented on frontend/src/pages/UserAdminPage/EditBalanceForm.tsx
> +    const loadOptions = debounce(async (globalFilter: string) => {
для loadOptions - useDebounce не подходит)
а вот в DebouncedInput можно интегрировать useDebounce

2023-04-07 05:58 UTC, alprtv commented on frontend/src/pages/UsersAdminPage/UsersAdminPage.tsx
> +    const handleSearchKey = useCallback((value: string) => {
да, ты прав

2023-04-07 07:42 UTC, nikolaas approved these changes

2023-04-07 07:42 UTC, merged