fix: statistic api methods
skondurushkin/ilp pull request #89
Opened 2023-04-08 09:26 UTC by stasian33rus

2023-04-08 10:38 UTC, nikolaas requested changes

2023-04-08 10:38 UTC, nikolaas commented on frontend/src/components/Chips.tsx
> +                        textBlack={primary}
свойство `black` устанавливает черный background кнопке. а ты ему еще еще и текст делаешь черным. Зачем? его же не видно будет

2023-04-08 10:38 UTC, nikolaas commented on frontend/src/utils/dateFormatters.ts
> +export const toIsoString = (date: Date): Date => {
вот это выглядит как что то страшное. есть же date-fns

2023-04-08 10:38 UTC, nikolaas commented on frontend/src/pages/AdminStatisticPage/AdminStatistic.tsx
> +        switch (balanceChip) {
я бы сделал так
```ts

// Это выносишь в утилиты, что то типа period.ts
interface Period {
    start: string;
    end: string;
}

type Interval = 'hour' | 'day' | 'week' | 'month' | 'year';

// сдвиг даты, Interval с минусом означает сдвиг в прошлое, без минуса - в будущее
type DateShift = Interval | `-${Interval}`;

function createPeriod(date: Date, shift: DateShift): Period {
    const first = format(date);
    const second = format(shiftDate(date, shift));// format из date-fns
    return shift.startsWith('-') ? { start: second, end: first} : { start: first, end: second };
}

function shiftDate(date: Date, shift: DateShift) {
    const past = shift.startsWith('-');
    const interval = past ? (shift.substring(1) as Interval) : (shift as Interval);
    const multiplier = past ? -1 : 1;

    switch (interval) {
        case 'day':
            return addDays(date, multiplier * 1); // addDays из date-fns
        case 'week':
            return addDays(date, multiplier * 7);
        case 'month':
            return addMonths(date, multiplier * 1); // addMonths из date-fns
        case 'year':
            return addYears(date, multiplier * 12); // addYears из date-fns
        default:
            throw new Error(`shifting a date to "${shift}" is not supported yet`);
    }
}

// А так оставляешь в компоненте
const now = new Date();
switch (balanceChip) {
    case 'day':
        return { ...createPeriod(now, '-day'), interval: 'hour' };
    case 'week':
        return { ...createPeriod(now, '-week'), interval: 'day' };
    default:
        return { ...createPeriod(now, '-month'), interval: 'day' };
}
```

2023-04-08 10:47 UTC, stasian33rus commented on frontend/src/utils/dateFormatters.ts
> +export const toIsoString = (date: Date): Date => {
ладно ладно) я не хотел большую либу тащить ради одной транички.
Добавлю

2023-04-08 10:50 UTC, stasian33rus commented on frontend/src/components/Chips.tsx
> +                        textBlack={primary}
primary меняет background на зелёный

2023-04-08 12:52 UTC, nikolaas requested changes

2023-04-08 12:52 UTC, nikolaas commented on frontend/src/components/Chips.tsx
> +                        textBlack={primary}
так у primary цвет текста и так черный

2023-04-08 12:52 UTC, nikolaas commented on frontend/src/utils/dateFormatters.ts
> +// export const toIsoString = (date: Date): Date => {
закомментированный код надо удалить

2023-04-08 12:52 UTC, nikolaas commented on frontend/src/utils/dateFormatters.ts
> +import addDays from 'date-fns/addDays';
файл переименуй в period.ts, это ведь уже не форматирование даты

2023-04-08 16:22 UTC, stasian33rus commented on frontend/src/components/Chips.tsx
> +                        textBlack={primary}
нет
    .btn-primary {
        @apply border-primary bg-primary;
    }

2023-04-09 14:23 UTC, alprtv approved these changes

2023-04-09 18:09 UTC, merged