feat(admin): add WriteOffsHistory
skondurushkin/ilp pull request #91
Opened 2023-04-08 18:31 UTC by alprtv

2023-04-08 20:42 UTC, nikolaas requested changes

2023-04-08 20:42 UTC, nikolaas commented on frontend/src/pages/ProductsAdminPage/ProductsAdminPage.tsx
> +                                <TypedLink to="/admin/products/edit/:productId" params={{ productId: id.toString() }}>
зачем ты клажешь кнопку в всылку? это тоже самое что делать кнопку в кнопке. Если тебе нужно чтобы ссылка выглядела как кнопка, там же у TypedLink есть свойство presentation со значеним button

```tsx
<TypedLink presentation="button" className="flex items-center gap-2">
    <EditSVG className="stroke-primary h-4 w-4" />
    <span className="text-small text-primary">Изменить</span>
</TypedLink>
```

2023-04-08 20:42 UTC, nikolaas commented on frontend/src/pages/UserAdminPage/BalanceHistory.tsx
> +                            <div>
вот этот див-обертка выглядит лишним тут

2023-04-08 20:42 UTC, nikolaas commented on frontend/src/pages/UserAdminPage/WriteOffsHistory.tsx
> +                        <div className="flex flex-col gap-2">
вот этот див вроде тоже как не нужен, это флекс контейнер, но в нем только один элемент, который будет работать и без флекс контейнера

2023-04-08 20:42 UTC, nikolaas commented on frontend/src/pages/UserAdminPage/WriteOffsHistory.tsx
> +                            <div>
этот див тоже не нужен

2023-04-09 04:02 UTC, alprtv commented on frontend/src/pages/UserAdminPage/BalanceHistory.tsx
> +                            <div>
да, от старого кода осталось, когда копировал не убрал

2023-04-09 04:03 UTC, alprtv commented on frontend/src/pages/UserAdminPage/WriteOffsHistory.tsx
> +                            <div>
да, от старого кода осталось, когда копировал не убрал

2023-04-09 04:04 UTC, alprtv commented on frontend/src/pages/ProductsAdminPage/ProductsAdminPage.tsx
> +                                <TypedLink to="/admin/products/edit/:productId" params={{ productId: id.toString() }}>
когда копировал не заметил, там просто до этого еще места были, сейчас найду их тоже поправлю

2023-04-09 04:21 UTC, alprtv commented
поправил все, влил

2023-04-09 04:21 UTC, alprtv commented on frontend/src/pages/UserAdminPage/WriteOffsHistory.tsx
> +                        <div className="flex flex-col gap-2">
да, осталось с старого кода

2023-04-09 04:21 UTC, merged